project_name: helm-test
release:
  github:
    owner: cedriclam
    name: helm-test
builds:
- goos:
  - linux
  goarch:
  - amd64
  - "386"
  main: .
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: helm-test
dockers:
  - image: cedriclam/helm-test
    goos: linux
    goarch: amd64
    goarm: ''
    binary: helm-test
    latest: true
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
