language: go
dist: trusty
go:
- 1.9.x
os: linux
services:
- docker
env:
  global:
  - TAG=${TRAVIS_TAG:=${TRAVIS_COMMIT}}
  - GH_URL=https://sdminonne.github.io/workflow-controller
  - secure: dmr0+m9v0Z7NF5gdhTD3ypLyEgZNwn+DZ8xweccNMei5boQaTqga2xTLBytZGzGmWFXuE7c15ettB34G7vg58D9CVoNuogF0M6/mkwKXWONyNKpOszl0HR+StAPNf+dIpAWTiob65vf2JjkJT7MXz4TxywHLgki70w6QByuI13oSweMc1EzrmAV+m7OxaMzDvjk8VBderhxHF8bTbCSnkvJt3IbRERFRcxU3pPZMUz/Dr2fuywHXujoKr2Iriprq7IMnneN1MKQya8zsTIpo3bBUaC13GAc4mcKC1ZWwBikgCEQtcrbWFFlaGRH2WuS6gbh2k3p3Z03/I1lAwUMX7/e6FWkHZn5mgZI4Q3zg12MrZVH7wfMU97RFv+4QPe3TlaFrazbnz9eMNgo/CYMFU8lfERGVT0mo6stJtP+vfWW4RiBJYJX9PKUWD3oPzhIBmvOCJfn7ZimstIWF+A3fJeZtlRK8gQ6sR3R8Dw08isHW3UVE8bvf6UHpAdZbXB8WtrK9n2Xh+xt25WSGsP0y/uiml3qwtCWsxt2m0wxOg3dOwhnPMZr1wZS6Ib9WqpM9+7LZunVU76b2xIz0bvaB9TPD8APKzI0F9xEtrOe4ak4J/DXDWm68Q5gI/8Nxtp003gDN8rAFUCpaTlkhfVFrxtUiAREgzE9bHcmjpUHDXeI=
install:
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
stages:
  - name: build
  - name: release
    if: tag IS present
  - name: deploy
    if: tag IS present
jobs:
  include:
    - stage: build
      name: build
      script:
        - CGO_ENABLED=0 GOOS=linux go build -i -installsuffix cgo -ldflags "-w" -o main .
        - docker build -t cedriclam/helm-test:$TAG .
    - stage: release
      script: |
          sed -i.bak "4s/.*/version: ${TAG}/" helm-test/Chart.yaml
          #docker push cedriclam/helm-test:$TAG
          helm package --version "$TAG" helm-test
          mv "helm-test-$TAG.tgz" docs
          helm repo index docs --merge docs/index.yaml
    - stage: deploy
      script: "echo deploy"
      deploy:
        - provider: releases
          api_key:
            secure: $API_TOKEN
          file: "docs/helm-test-$TAG.tgz"
          on:
            tags: true